#!/bin/bash

cluster=$1
if [ ! -z $cluster ]; then
    echo Getting cluster config for $cluster ...
    mkdir $cluster
    export KUBECONFIG=`pwd`/$cluster/kube-config
    ibmcloud cs cluster config --admin --yaml --cluster $1 
else
    echo Need cluster name. ex - getconfig cloudzcp-mcm-dev
fi
