#!/bin/bash
kubectl config set-context --current --namespace $1

context=`kccc`

if [[ $context == arn* ]] ;
then
    context=`echo $context | cut -f 2 -d '/'`
else
    context=`echo $context | cut -f 1 -d '/'`
fi

namespace=`kgn`

export PS1="${ret_status}%{$fg[red]%}${context} %{$fg[yellow]%}[${namespace}] %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)"
