#!/bin/bash
current=`pwd`
yaml=`ls kube-config*`

if [ $? -eq 1 ];then
  return 1
fi

echo KUBECONFIG=$current/$yaml

export KUBECONFIG=$current/$yaml

context=`kubectl config current-context`

if [[ $context == arn* ]] ;
then
    context=`echo $context | cut -f 2 -d '/'`
else
    context=`kccc | cut -f 1 -d '/'`
fi

namespace=`kgn`

export PS1="${ret_status}%{$fg[red]%}${context} %{$fg[yellow]%}[${namespace}] %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)"
